Document: purple-lurch
Title: Debian purple-lurch Manual
Author: <insert document author here>
Abstract: This manual describes what purple-lurch is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/purple-lurch/pidgin-plugin-lurch.sgml.gz

Format: postscript
Files: /usr/share/doc/purple-lurch/pidgin-plugin-lurch.ps.gz

Format: text
Files: /usr/share/doc/purple-lurch/pidgin-plugin-lurch.text.gz

Format: HTML
Index: /usr/share/doc/purple-lurch/html/index.html
Files: /usr/share/doc/purple-lurch/html/*.html
